// @ts-nocheck
// AUTO-GENERATED by Flow-Guard /generate — do not edit by hand.
// Human settings live in playwright.config.base.ts
import { defineConfig, devices } from '@playwright/test';
import { baseConfig } from './playwright.config.base';

export default defineConfig({
  ...baseConfig,
  use: {
    ...baseConfig.use,
    baseURL: 'http://localhost:3000',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
});
