// @ts-nocheck
// AUTO-GENERATED by Flow-Guard /generate — do not edit by hand.
// Human settings live in playwright.config.base.ts
import { defineConfig } from '@playwright/test';
import { baseConfig } from './playwright.config.base';

export default defineConfig({
  ...baseConfig,
  testDir: '.',
  use: { ...baseConfig.use, locale: 'zh-TW', baseURL: 'http://localhost:3000' },
  projects: [
    { name: 'tsso-setup', testMatch: /playwright[\/\\]setup[\/\\]tsso\.setup\.ts/ },
    {
      name: 'mock-user-setup',
      testMatch: /tests[\/\\]generated[\/\\]20260529-002312[\/\\]mock-user\.setup\.ts/,
      dependencies: ['tsso-setup'],
      use: { storageState: 'playwright/.auth/tsso-base.json' },
    },
    {
      name: 'chrome-admin',
      testMatch: /tests[\/\\]generated[\/\\]20260529-002312[\/\\]flow\.admin\.spec\.ts/,
      dependencies: ['mock-user-setup'],
      use: { channel: 'chrome', storageState: 'tests/generated/20260529-002312/.auth/state-admin.json' },
    },
    {
      name: 'chrome-editor',
      testMatch: /tests[\/\\]generated[\/\\]20260529-002312[\/\\]flow\.editor\.spec\.ts/,
      dependencies: ['mock-user-setup'],
      use: { channel: 'chrome', storageState: 'tests/generated/20260529-002312/.auth/state-editor.json' },
    },
    {
      name: 'chrome-viewer',
      testMatch: /tests[\/\\]generated[\/\\]20260529-002312[\/\\]flow\.viewer\.spec\.ts/,
      dependencies: ['mock-user-setup'],
      use: { channel: 'chrome', storageState: 'tests/generated/20260529-002312/.auth/state-viewer.json' },
    },
  ],
});
