// @ts-nocheck
// AUTO-GENERATED by Flow-Guard /generate — do not edit by hand.
// Human settings live in playwright.config.base.ts
import { defineConfig, devices } from '@playwright/test';
import { baseConfig } from './playwright.config.base';

export default defineConfig({
  ...baseConfig,
  testDir: './tests/generated/20260527-005133',
  projects: [
    {
      name: 'chromium',
      testMatch: /flow\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        baseURL: 'https://www.saucedemo.com',
        storageState: 'playwright/.auth/state-standard.json',
      },
    },
  ],
});
